ERP_mecanica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacao/', include('autenticacao.urls')),
    path('funcionarios/', include('app_funcionario.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('servicos/', include('app_servicos.urls')),
]

app_funcionario/urls.py
from django.urls import path, include
from . import views
urlpatterns = [

    #path('get_parametros/', views.get_parametros, name='get_parametros'),
    path('', views.funcionarios, name='funcionarios'),
    path('ajax_validacao/',views.valida_funcionarios,name='ajax_validacao'),
    path('apaga_funcionario/',views.apaga_funcionarios,name='apaga_funcionario'),
    #path('editar_funcionario/',views.editar_funcionarios,name='editar_funcionario'),
]

app_funcionario/models.py
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models

class Funcionario(models.Model):
    class funcaoChoices(models.TextChoices):
        GERENTE =               1, 'Gerente'
        AUXILIAR_TEC =          2, 'Auxiliar Técnico'
        MECANICO =              3, 'Mecânico'
        ENGENHEIRO_MECANICO =   4, 'Engenheiro Mecânico'
        JOVEM_APRENDIZ =        5, 'Jovem Aprendiz'
        ATENDENTE =             6, 'Atendente'
        LAVADOR =               7, 'Lavador'

    nome = models.CharField(max_length=60)
    cpf = models.CharField(max_length=11, unique=True,null=False,blank=False)
    funcao = models.CharField(max_length=60, choices= funcaoChoices.choices)
    tag_id = models.CharField(max_length=11,unique=True, null=True)

    def __str__(self) ->str:
        return self.nome


class HistoricoFuncionarios(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateTimeField(default=datetime.datetime.now(tz=timezone.utc))
    descricao = models.CharField(max_length=255)
    acao = models.CharField(max_length=30)

app_funcionario/views.py
import re

from django.contrib.auth.decorators import login_required
from django.db.transaction import on_commit
from django.http import JsonResponse
from django.core import serializers
import json
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

from .models import Funcionario, HistoricoFuncionarios
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.messages import error, success


# def get_parametros(request):
#     if request.method == "POST":
#         return render(request,'funcionarios.html')
#     else:
#         return render(request, 'funcionarios.html')
@login_required(login_url="/autenticacao/login")
def funcionarios(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        funcao = request.POST.get('funcao')
        cpf = str(request.POST.get('cpf'))

        cpf_valid = re.sub('[.,-]', '', cpf)

        funcionario = Funcionario.objects.filter(cpf=cpf)
        if not funcionario:
            usuario = Funcionario(nome=nome, cpf=cpf_valid, funcao=funcao)
            usuario.save()

        return render(request, 'funcionarios.html', grid_funcionarios())
    else:
        # print(request.user.pk)
        return render(request, 'funcionarios.html', grid_funcionarios())


@csrf_exempt
def apaga_funcionarios(request):
    usuario = request.user
    if request.method == 'POST':
        pk_funcionario = request.POST.get('pk_funcionario')

        funcionario = Funcionario.objects.get(id=pk_funcionario)
        if funcionario:

            historico = HistoricoFuncionarios(
                            usuario=usuario,
                            descricao=u"APAGOU O USUÁRIO {}[{}]".format(funcionario.nome, funcionario.pk),
                            acao='APAGOU'
                        )
            funcionario.delete()
            historico.save()

            result = {'resultado': 'true'}
        else:
            result = {'resultado': 'false'}

    return JsonResponse(result)


# -----------------------------------------------------------------------------------------------------------------------
#valida o cpf do funcionario
# -----------------------------------------------------------------------------------------------------------------------
def valida_funcionarios(request):
    if request.method == 'POST':
        cpf = request.POST.get('cpf')
        funcionario = Funcionario.objects.filter(cpf=cpf)
        if funcionario:
            validacao = json.loads(serializers.serialize('json', funcionario))[0]['fields']
            for funcao in Funcionario.funcaoChoices.choices:
                if funcao[0] == validacao['funcao']:
                    validacao['funcao'] = funcao[1]
        elif len(cpf) != 11:
            validacao = {'erro': 'CPF Inválido'}
        else:
            validacao = {'pass': None}
    return JsonResponse(validacao)

# -----------------------------------------------------------------------------------------------------------------------
# Retorna o context para o grid funcionarios com os dados atualizados
# -----------------------------------------------------------------------------------------------------------------------
def grid_funcionarios():
    funcionarios = Funcionario.objects.all()

    context = dict(
        funcionarios=funcionarios,
        choices=Funcionario.funcaoChoices
    )
    return context

app_funcionario/templates/funcionarios.html
{% extends 'base.html' %}
{% load static %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static 'funcionarios/css/funcionarios.css' %}">
{% endblock %}

{% block 'dashboard' %}
    <div class="container">
        <h2>Funcionários</h2><br>
{#        <button style="color: #FFFFFF"  type="button" class="btn btn-modal" data-toggle="modal" data-target="#modalfuncionarios">#}
{#          Incluir#}
{#        </button>#}
        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Ações
            </button>
            <div style="text-align: center" class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                 <a title="Adicionar Funcionário" class="dropdown-item acoes" class="btn btn-modal" data-toggle="modal" data-target="#modalfuncionarios" href="#">
                     <i class="fa-solid fa-user-plus"></i> Adicionar
                 </a>
                <hr>
                 <a title="Imprimir" class="dropdown-item acoes" class="btn btn-modal" data-toggle="modal" data-target="#modalfuncionarios" href="#">
                     <i class="fa-solid fa-print"> </i>  Imprimir
                 </a>
            </div>
          </div>
    </div>
    <div class="container">
        {% include 'grid_funcionarios.html' %}
    </div>
{% endblock %}
{% block 'modais' %}
    {% include 'modal_funcionarios.html' %}
{% endblock %}
{% block 'scripts' %}
    <script src="{% static 'funcionarios/js/funcionarios.js' %}"></script>
{% endblock %}

app_funcionario/templates/grid_funcionarios.html
<table id="table_id" class="table table-dark paginated" >
    <thead>
    <tr>
        <th scope="col">Código</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Função</th>
        <th scope="col">Ações Individuais</th>
    </tr>
    </thead>
    <tbody>
        {% for funcionario in funcionarios %}
            <tr>
                <th scope="row">{{ funcionario.pk }}</th>
                <td>{{ funcionario.nome }}</td>
                <td>{{ funcionario.cpf }}</td>
                <td>{{ funcionario.get_funcao_display }}</td>
                <td>
                    <div class="btn-group" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fa-solid fa-plus"></i>
                        </button>
                        <div style="text-align: center" class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                          <a id="apagar" title="Excluir Funcionário" class="dropdown-item acoes" onclick="apaga_funcionario({{ funcionario.pk }})" href="javascript:void(0)">
                              <i class="fa-solid fa-trash-can"></i> Apagar
                          </a>
                          <a id="alterar" title="Alterar Funcionário" class="dropdown-item acoes" href="javascript:void(0)" onclick="editar_funcionario({{ funcionario.pk }})"
                             class="btn btn-modal" data-toggle="modal" data-target="#modalfuncionarios">
                              <i class="fa-solid fa-pencil"></i> Editar
                          </a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

app_funcionario/templates/modal_funcionarios.html
<!-- Modal -->
<div class="modal fade" id="modalfuncionarios" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" >Incluir Novo Funcionário</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <form class="needs-validation" action="{% url "funcionarios" %}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
                <div class="col-md">
                    <label for="nome">Nome:</label>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" id="nome" required>
                </div>
                <div class="col-md">
                    <label for="cpf">CPF:</label>
                    <input type="text" class="form-control" placeholder="cpf" name="cpf"  id="cpf" required>
                    <div id="validacaoCpf"></div>

                </div>
                <div class="col-md">
                    <label for="funcao">Função</label>
                    <select id="funcao" class="form-control" aria-label="Default select example" name="funcao">
                      <option selected value="">----</option>
                        {% for funcao in choices %}
                             <option value="{{ funcao }}">{{ funcao.label}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button id="salvar" style="color: #FFFFFF; background-color: #61a52a; border-color: #60a42a" type="submit" class="btn btn-primary" >Salvar</button>
            </div>
        </form>
    </div>
  </div>
</div>